server:
#  노트북 포트
#  port: 8080
#  데스크탑 포트
  port: 9000
  shutdown: graceful

spring:
  application:
    name: jutopia
  profiles:
    active: local
    group:
      "local": "local"
      "prd": "prd"
  thymeleaf:
    prefix: classpath:templates/main
    suffix: .html
    cache: false
    check-template-location: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

management:
  endpoints:
    web:
      exposure:
        include: refresh

auth:
  account:
    path:
      - '/my-content'
      - '/my-content/**'
      - '/stream'
---

spring:
  config:
    activate:
      on-profile: "local"
    import:
      - classpath:config/local/config.yml
      - classpath:config/local/api-config.yml
      - classpath:config/local/datasource.yml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info