logging:
  level:
    com.lgtvod.contents: DEBUG
    org.hibernate.type: trace
    org.hibernate.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.pretty: TRACE

jutopia:
  jwt:
    secret: d1b014505346f9fdafbdf571de8f8dabebd71c525f99528fec2b0a657366ec5a
    refresh:
      duration: 36000
    access:
      duration: 60
  refresh:
    jwt:
      secret: jutapia-JbProject-refreshSecret-1214
      duration: 36000
  access:
    jwt:
      secret: jutapia-JbProject-accessSecret-1214
      duration: 3600

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full

#spring:
#  cloud:
#    openfeign:
#      client:
#        config:
#          default:
#            connect-timeout: 5000
#            read-timeout: 5000
#      circuitbreaker:
#        enabled: true

#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeoutDuration: 5s
#        cancelRunningFuture: true

#cloud:
#  aws:
#    s3:
#      public-bucket: ${data.S3_DATA}
#      private-bucket: ${data.S3_DATA}
#      max-upload-size: 10485760
#      public-url: none
#      region: ap-northeast-2
